
let items = [{
    id: 1,
    name: 'bag',
    image: './img/bag.jpg',
    viewed: 0,
    votes: 0
}, {
    id: 2,
    name: 'banana',
    image: 'img/banana.jpg',
    viewed: 0,
    votes: 0,
}, {
    id: 3,
    name: 'bathroom',
    image: 'img/bathroom.jpg',
    viewed: 0,
    votes: 0,
}, {
    id: 4,
    name: 'boots',
    image: 'img/boots.jpg',
    viewed: 0,
    votes: 0
}, {
    id: 5,
    name: 'breakfast',
    image: 'img/breakfast.jpg',
    viewed: 0,
    votes: 0
}, {
    id: 6,
    name: 'bubblegum',
    image: '/img/bubblegum.jpg',
    viewed: 0,
    votes: 0
}, {
    id: 7,
    name: 'chair',
    image: '/img/cthulhu.jpg',
    viewed: 0,
    votes: 0
}, {
    id: 8,
    name: 'dog-duck',
    image: '/img/dog-duck.jpg',
    viewed: 0,
    votes: 0
}, {
    id: 9,
    name: 'dragon',
    image: 'img/dragon.jpg',
    viewed: 0,
    votes: 0
}, {
    id: 10,
    name: 'pen',
    image: '/img/pen.jpg',
    viewed: 0,
    votes: 0
}, { 
    id: 11,
    name: 'pet-sweep',
    image:'/img/pet-sweep.jpg',
    viewed: 0,
    votes: 0
}, {
    id: 12,
    name: 'scissors',
    image: '/img/scissors.jpg',
    viewed: 0,
    votes:  0
}, {
    id: 13,
    name: 'shark',
    image: '/img/shark.jpg',
    viewed: 0,
    votes: 0
}, {
    id: 14,
    name: 'sweep',
    image: '/img/sweep.jpg',
    viewed: 0,
    votes: 0
}, {
    id: 15,
    name: 'tauntaun',
    image: '/img/tauntaun.jpg',
    viewed: 0,
    votes: 0
}, {
    id: 16,
    name: 'unicorn',
    image: '/img/unicorn.jpg',
    viewed: 0,
    votes: 0
}, {
    id: 17,
    name: 'usb',
    image: '/img/usb.gif',
    viewed: 0,
    votes: 0
}, {
    id: 18,
    name: 'water-can',
    image: 'img/water-can.jpg',
    viewed: 0,
    votes:  0
}, {
    id: 19,
    name: 'wine-glass',
    image: 'img/wine-glass.jpg',
    viewed: 0,
    votes: 0
}];

export default items
